[Fix] #111 - RoomScanInfoView에 예시 3d모델 추가
DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous pull request #112
Opened 2024-12-26 02:44 UTC by WooFeather

close #111

## *⛳️ Work Description*
- RoomScanInfoView에 예시 3d모델을 추가했습니다.

## *📸 Screenshot*
| iPhone 15 Pro |
| -- |
| ![스크린샷, 2024-12-26 오전 11 43 33](https://github.com/user-attachments/assets/400f37e8-25bd-42c0-b654-49ff37b25973) |

## *📢 To Reviewers*
-

## *✅ Checklist*
- [ ] 주석 및 프린트문 제거 확인.
- [ ] 컨벤션 준수 확인.

2024-12-27 03:36 UTC, Naknakk requested changes
좋습니당 뷰 따로 뺀 것도 좋네요.
근데 모델 이미지가 화질이 너무 안좋은데, 우선 PNG로 넣는 만큼 x2, x3배 이미지도 넣어줘야 할 것 같아용!
그리고, 사실은 이미지 크기 자체가 피그마에서도 원래 너무 작아서, 피그마에서 이미지를 export할 때 x4, x5, x6으로 뽑은 뒤 각각을 xcode의 x1, x2, x3에 넣어주면 좋을 것 같습니다!

PNG는 반드시 x1, x2, x3이미지가 들어가야 하는 것 항상 기억해주세용!

2024-12-28 14:49 UTC, lemonisgreen approved these changes
흑흑 추가된 거 너무 좋아요~~!! 이제 나리도 기죽지 않고 기존 세입자에게 구조만 스캔하는 거라고 당당하게 이야기할 수 있겠군요!! 고생하셨습니다~~!!

2024-12-29 11:06 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/RoomScan/exRoomScanInfo.imageset/Contents.json
> +    }
1x, 2x, 3x 이미지 추가했습니다!

2024-12-29 18:14 UTC, Naknakk approved these changes
LGTM!

2024-12-30 01:22 UTC, merged