[Feat] 룸플랜 기능구현
DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous pull request #25
Opened 2024-11-19 15:56 UTC by WooFeather

close #24 

## *⛳️ Work Description*
- 룸플랜과 위치정보를 위한 plist 세팅
- 

## *📸 Screenshot*
| iPhone SE 3rd | iPhone 13 mini | iPhone 15 Pro | iPhone 15 Pro Max |
| -- | -- | -- | -- |
| ![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-10-05 at 17 07 43](https://github.com/user-attachments/assets/44f72605-a7d6-4be5-8616-8848a06c008d) | ![Simulator Screen Recording - iPhone 13 mini - 2024-10-05 at 17 08 26](https://github.com/user-attachments/assets/0af5f21e-aace-4e11-b316-9dd537188aa4) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-10-05 at 17 09 24](https://github.com/user-attachments/assets/ef89ef84-aaa8-4d01-b172-7ba26bfa967a) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-10-05 at 17 10 12](https://github.com/user-attachments/assets/87edd9e5-885b-4dd5-be7a-e8dc296b116b) |

## *📢 To Reviewers*
-

## *✅ Checklist*
- [ ] 주석 및 프린트문 제거 확인.
- [ ] 컨벤션 준수 확인.

2024-11-19 16:34 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Data/Model/SampleRoom.swift
> +}
RoomPlan기능 테스트를 위한 Sample Room Model입니다.
나기가 작업하고 있는 구조화작업이 끝나면 수정(혹은 삭제)할 예정입니다.

2024-11-19 17:17 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Data/Model/SampleRoom.swift
> +    }
SwiftData가 UIImage를 지원하지 않아서 이미지를 Data타입으로 저장하는데, 이를 뷰에서 불러올 때 UIImage로 변환해서 보여주는 계산속성입니다.

2024-11-20 03:41 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/ContentView.swift
> +            }
일단 바로 RoomScanView로 이동하기 위해 ContentView에 NavigationLink를 만들어놨습니당

2024-11-20 03:41 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
> +                    .ignoresSafeArea()
RoomScan을 하는 녀석입니다.

2024-11-20 03:43 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
> +
RoomScanView에서 저장하기를 누르면 3D 모델 화면이 캡쳐되고, 배경을 제거하는 동작을 합니다.

2024-11-20 03:44 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
> +                            }
모델이 정상적으로 랜더링되었을 경우 ResultCardView가 sheet로 뜹니다.

2024-11-20 08:09 UTC, lemonisgreen commented on ZipZipSa/ZipZipSa/Data/Model/SampleRoom.swift
> +}
삭제티비...

2024-11-20 08:15 UTC, Naknakk requested changes
킥 킥

2024-11-20 08:15 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
S2
지금은 테스트용 코드지만 나중에는 코드 정리해서 작성해주세요~~ 코드 리뷰를 위해서도!

2024-11-20 08:15 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Presentation/ContentView.swift
S1
이런 부분은 나중에 결국 수정되어야 하기 때문에 컨텐츠 뷰에서 불러오는 뷰를
RoomScanView(hasRoomModel: $hasRoomModel)
로 바꿔서 테스트 해보고, add 는 하지 않은채로 커밋을 모두 작성해서 변경사항이 없도록 하면 좋을 것 같아용~

2024-11-20 08:15 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +}
S1
신기방구 하네요? 이런건 Presentation 폴더에 custom 폴더 만들어서 추가해놔도 좋을 것 같아요 !

2024-11-20 08:15 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Resource/Extension/UIImage++.swift
S1
UIImage ++ 아니고 +래요~

2024-11-20 08:15 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Resource/Extension/UIView++.swift
S1
UIView++래요 ~

2024-11-20 08:15 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Resource/Extension/View++.swift
S1
이것도요~

2024-11-20 08:23 UTC, lemonisgreen approved these changes
페더쿵야 수고했다요~~~!!!!

2024-11-21 00:17 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/ContentView.swift
그렇게 할까말까 고민했었는데! 생각해보니 그게 더 좋은방법이겠군👍

2024-11-21 11:19 UTC, Naknakk approved these changes
고생했습니다 !!
룸플랜 클래스는 아마 제가 직접 다루진 않을 것 같아서 페더가 만든대로 써도 될 것 같아요 !!

2024-11-21 13:44 UTC, merged