[Feat] #26 - 주변시설 불러오기 기능
DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous pull request #27
Opened 2024-11-20 08:47 UTC by WooFeather

close #26 

## *⛳️ Work Description*
- GoogleMaps SPM 추가

## *📸 Screenshot*
| iPhone SE 3rd | iPhone 13 mini | iPhone 15 Pro | iPhone 15 Pro Max |
| -- | -- | -- | -- |
| ![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-10-05 at 17 07 43](https://github.com/user-attachments/assets/44f72605-a7d6-4be5-8616-8848a06c008d) | ![Simulator Screen Recording - iPhone 13 mini - 2024-10-05 at 17 08 26](https://github.com/user-attachments/assets/0af5f21e-aace-4e11-b316-9dd537188aa4) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-10-05 at 17 09 24](https://github.com/user-attachments/assets/ef89ef84-aaa8-4d01-b172-7ba26bfa967a) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-10-05 at 17 10 12](https://github.com/user-attachments/assets/87edd9e5-885b-4dd5-be7a-e8dc296b116b) |

## *📢 To Reviewers*
-

## *✅ Checklist*
- [ ] 주석 및 프린트문 제거 확인.
- [ ] 컨벤션 준수 확인.

2024-11-21 18:40 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +    ]
`facilityChecker`: API KEY를 이용해서 Google Place API와 통신해서 주변 시설을 확인하는 `FacilityChecker(apiKey:)`함수를 의미합니다.
`keywords`: 구글맵에 검색할 검색 키워드 배열입니다.
`facilityIcons`: 각 키워드에 매칭되는 아이콘을 할당해놓은 딕셔너리입니다.

2024-11-21 18:40 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +                }
매칭된 시설 아이콘을 ForEach를 통해 보여줍니다.

2024-11-21 18:43 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +        }
ShareCard가 onAppear될 때 `checkFacilities(at: , for: )`함수를 실행해서, 그 결과를 `availableFacilities`배열에 담습니다.

2024-11-22 05:35 UTC, Naknakk requested changes
고생했습니당~~ 헤헷 리뷰 참고해주세용~~~

2024-11-22 05:35 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +    ]
S1
이런 부분은 enum으로 만들어서 빼면 좋을 것 같아요 !.! 제가 만든 ChecklistCategory 이런 enum 한번 보고 참고해서 쓰면 좋을 것 같아용!
Constant 폴더에 넣으면 어떨까용 !

2024-11-22 05:36 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Resource/Manager/FacilityChecker.swift
> +}
S1
얘네들도 모델로 옮겨서 파일을 만들어줘도 좋을 것 같아요! 
lat나 lng처럼 줄임말 사용은 지양하는게 좋을 것 같아용!

2024-11-22 14:14 UTC, WooFeather commented on ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
> +    @State private var hasRoomModel: Bool = false
헤헤 이건 사용하지 않는 변수 삭제라는 커밋에서 삭제했답니다!
처리완료~

2024-11-23 04:34 UTC, lemonisgreen approved these changes
넥슨은 다이소를 내놓아라! 내놓아라!

2024-11-23 04:46 UTC, Naknakk requested changes
고생했습니당 ! 몇개만 더 확인해주세용!!

2024-11-23 04:46 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +    let facilities: [Facility] = [.lundry, .convenienceStore, .mart, .hospital, .pharmacy, .park, .daiso]
S1
이렇게 매번 변수를 만들기 보다, enum에 CaseIterable을 채택해서 쓰는건 어떨까요!

2024-11-23 04:46 UTC, Naknakk commented on ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
> +    @State private var hasRoomModel: Bool = false
S2
삭제되지 않고 남아있는 것 같아요 !

2024-11-23 06:22 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Resource/Manager/FacilityChecker.swift
> +}
lat나 lng은 Google Places API의 response구조에 저렇게 적혀있어서 변수명을 수정하면 디코딩 오류가 납니다..! 그래서 일단 response의 변수명 그대로 lat와 lng를 사용한건데 더 좋은 방법이 있으면 반영하겠습니다!

2024-11-23 06:23 UTC, WooFeather commented on ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
> +    @State private var hasRoomModel: Bool = false
아 제가 다른거랑 헷갈렸네요! 원래 이 변수는 모델이 있을 경우에만 결과카드에  보여주기 위해 만들었었는데, model자체가 옵셔널이고 if let으로 처리하면 굳이 필요하지 않는 변수라서 이번에 삭제했습니다!

2024-11-23 09:13 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Resource/Manager/FacilityChecker.swift
> +    func checkFacilities(at location: CLLocationCoordinate2D, for keywords: [String], completion: @escaping ([String: Bool]) -> Void) {
제가 이렇게 저렇게 해봤는데 컴플리션 핸들러를 썼을떄보다 뭔가 부자연스럽다고 해야되나.,?
일단 원래대로 하고 같이 봐주시면 좋겠어요!

2024-11-23 13:56 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Resource/Manager/FacilityChecker.swift
> +    func checkFacilities(at location: CLLocationCoordinate2D, for keywords: [String], completion: @escaping ([String: Bool]) -> Void) {
일단 적용을 하긴 했는데 그렇게 좋은 코드인지는.. 잘 모르겠습니다!
함 봐주시지요!

2024-11-23 14:21 UTC, Naknakk requested changes
고생했습니다 ..! 
진짜진짜 몇개만 더 확인해주세오. . . 헤헤

2024-11-23 14:21 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
S2
신기한 방식인데 나쁘지 않은 것 같아용 ~ 근데 추가적인 case가 존재할 수 있는 baseURL인지 궁금하네요...?
baseURL은 "https://maps.googleapis.com/maps/api/" 여기까지여야 할 것 같기도 하구요 ..!

2024-11-23 14:21 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Data/Foundation/FacilityChecker.swift
> +    private func fetchFacility(for keyword: String, at location: CLLocationCoordinate2D) async throws -> Bool {
S1
두 메서드의 네이밍 방식이나 매개변수 넣는 순서를 통일하면 좋을 것 같습니당
checkFacility, checkFacilities 이런 느낌이면 서로 다른 메서드다 라는 느낌 없이, 키워드 하나일 때, 여러 개일 때 쓰는 메서드구나~ 싶을 것 같아요.
매개변수도 로케이션을 먼저 넣거나 키워드를 먼저 넣거나 두 개의 순서가 통일되면 좋을 것 같아용

2024-11-23 14:21 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Data/Foundation/FacilityChecker.swift
> +        let (data, _) = try await URLSession.shared.data(from: url)
S2
해당 try의 에러도 페더가 정의한 NetworkError로 처리해주면 좋을 것 같기도요! 지금은 아무것도 처리가 안되어있어서 원래 try의 에러가 전파되긴 하겠지만.. 우리가 설정한 에러로 받는게 다루기 편하니까용!~!

저는 이런 경우에는 
guard let (data, _) = try? await URLSession.shared.data(from: url) else {
    throw NetworkError.networkError(keyword: keyword, description: error.localizedDescription)
}
이렇게 처리할 것 같아요!

2024-11-23 14:21 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Data/Model/PlaceRespnse.swift
> +}
S1
전의 애공 코드를 빌려오자면, Codable한 경우  enum CodingKeys: String, CodingKey를 사용할 수 있답니다!
이건 서버에서 보내주는 키 값을 맞춰주기 위해 쓰는건데요, 서버에서 보내주는 값을 rawValue로 넣어주면 클라단에서는 우리가 원하는 변수 명을 쓰면서 서버 키 값을 맞춰주기까지 동시에 된답니당!

```suggestion
struct Location: Codable {
     let latitude: Double
     let longitude: Double

    enum CodingKeys: String, CodingKey {
        case latitude = "lat"
        case longitude = "lng"
    }
}
```

2024-11-23 14:21 UTC, Naknakk commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +        }
S1
이것도 애공때의 코드인데, async, await로 코드를 짰다면, onAppear말고 이렇게 써보는건 어떨까용
DispatchQueue.main.async 사용 없이 State 값을 바꿀 수 있도록 도와준답니다!


```swift
             .task {
                await fetchData()
            }
```

```swift
    func fetchData() async {
        do {
            self.places = try await placeService.getPlaces()
            self.user = try await userService.getUser(id: StringLiterals.Network.dummyUserID)
        } catch {
            print(error)
        }
    }
 ```

2024-11-24 10:53 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
사실 어케해야할지 감이 잘 안잡혀서 이렇게 해놓긴했는데, 추후에 통근거리 계산 API와 통신하려면 baseURL이 좀 수정되어야 할거같네요!

2024-11-24 10:55 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Data/Model/PlaceRespnse.swift
> +}
오오 코딩키가 이럴때 쓰는거균뇨! 또 하나 배워갑니다 👍

2024-11-24 11:48 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Data/Model/PlaceRespnse.swift
> +}
CodingKeys 적용했습니다!

2024-11-24 11:49 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
> +        }
onAppear에서 task로 수정했습니다.
다만, 어떤 차이가 있는지 모르겠는데 네트워크 에러가 종종 발생하긴합니다.
치명적으로 막 시설을 못불러오고 그런건 아닌거같은데, 일단 이대로 진행하고 추후 계속 수정해야할것 같습니다

2024-11-24 11:50 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
> +    }
추후 GoogleDistance Matrix API(통근거리계산)과 함께 사용하기 위해 baseURL을 수정했습니다.

2024-11-24 15:24 UTC, Naknakk approved these changes
고생했습니다~~~ 진짜 신기한 기능 잘 구현한 것 같아요 빠샤뺘샤샷나이스샷

2024-11-24 15:57 UTC, merged