Design/#30 - MainView 구현
DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous pull request #32
Opened 2024-11-23 13:38 UTC by lemonisgreen

## *⛳️ Work Description*
- MainView 기본 틀 구현 및 프로퍼티 분리
- 집집사의 팁 random auto slide구현

## *📸 Screenshot*
| iPhone SE 3rd | iPhone 13 mini | iPhone 15 Pro | iPhone 15 Pro Max |
| -- | -- | -- | -- |
|![Simulator Screen Recording - iPhone 16 Pro - 2024-11-23 at 22 34 23](https://github.com/user-attachments/assets/9a977ee7-334f-4311-9b1a-cce6badaa741) | 

## *📢 To Reviewers*
- 최근 본 집에 본 집 더미데이터 채우기
- 디자이너와 상의 후 디테일 조금씩 더 손봐야 합니다!!

## *✅ Checklist*
- [ ] 주석 및 프린트문 제거 확인.
- [ ] 컨벤션 준수 확인.

2024-11-23 13:42 UTC, lemonisgreen commented on ZipZipSa/ZipZipSa/Data/Model/ZipZipSaTip.swift
> +      }
이 부분은 집집사 팁을 랜덤으로 호출하되, 팁 리스트가 꼭 한 번씩은 보여지게 하기 위해서 작성한 코드입니다. 클로드 친구가 도움을 주었고요, 보다 명확한 이해를 돕기 위해 클로드 친구의 설명을 함께 첨부합니다. 

클로드 가라사대:
displayedTips라는 private 변수를 추가하여 현재 보여줄 팁들을 저장합니다.
getRandomText()가 호출될 때:
displayedTips가 비어있으면 원본 tips 배열을 섞어서(shuffled()) 새로 채웁니다.
섞인 배열에서 첫 번째 항목을 제거하고 반환합니다(removeFirst()).
모든 팁이 한 번씩 표시된 후에는 다시 배열을 섞어서 새로운 순서로 시작합니다.
이렇게 하면 모든 팁이 랜덤한 순서로 한 번씩 표시되고, 한 바퀴를 다 돌면 다시 새로운 랜덤 순서로 시작하게 됩니다.

2024-11-23 13:43 UTC, lemonisgreen commented on ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
색상 및 폰트 적용하기 전입니다!

2024-11-24 10:45 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Data/Model/ZipZipSaTip.swift
> +      }
S3: 오홍 재밌네요! 첫 번째 항목을 제거하는 이유는 한번 보여진 친구는 다시 안보이도록 하는건가요?

2024-11-24 10:49 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
> +        }
S2: 본 집이 있을 경우의 분기처리는 추후 추가될 예정인가요?

2024-11-24 10:50 UTC, WooFeather commented on ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
> +        NavigationLink(destination: SettingView()) {
S1: SettingView가 아니라 EssentialInfoView로 수정해주세요!

2024-11-24 10:51 UTC, WooFeather requested changes
수고하셨습니다!
코멘트 확인 부탁드립니다 :)

2024-11-24 14:26 UTC, lemonisgreen commented on ZipZipSa/ZipZipSa/Data/Model/ZipZipSaTip.swift
> +      }
맞습니다! 랜덤으로 배열된 순서 중 첫 번째 친구들을 제거하고, 더이상 보여질 문장이 남아있지 않으면 새로 셔플된 배열을 가져오는 함수입니다!

2024-11-24 14:27 UTC, lemonisgreen commented on ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
> +        NavigationLink(destination: SettingView()) {
히히 넵! 일단은 만들어진 뷰 아무거나에 연결시켜뒀는데, EssentialInfoView 만들어서 연결시켜두도록 하겠습니다~!!

2024-11-24 14:30 UTC, lemonisgreen commented on ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
> +        }
네 그렇습니다!_! 추후에 데이터 처리 방식이 정해지면 추가해두도록 하겠습니다!

2024-11-25 15:36 UTC, Naknakk approved these changes
고생했습니당! 추후에  문구들은  StringLiteral로 빼주세요!!

2024-11-27 08:23 UTC, WooFeather approved these changes
앞구르기 하면서 봐도 어푸르브입니다.
따봉티비 👍

2024-11-27 09:01 UTC, merged